config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get '/riyo_kiyaku', to: 'static_pages#riyo_kiyaku'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: "users/registrations",
    sessions: "users/sessions",
    passwords: "users/passwords"
  }
  devise_scope :user do
    get    'users/signup', to: 'devise/registrations#new',    as: :new_user
    post   'users/signup', to: 'devise/registrations#create', as: :user_signup
    get    'users/login',  to: 'devise/sessions#new',         as: :new_user_login
    post   'users/login',  to: 'devise/sessions#create',      as: :user_login
    delete 'users/logout', to: 'devise/sessions#destroy',     as: :user_logout
  end

  resources :users,           only: [:index, :show] do
    member do
      get :edit_password
      patch :update_password
      get :following
      get :followers
      get :favorites
    end
  end

  resources :posts,           only: [:show, :new, :create, :destroy] do
    resources :comments,        only: [:create]
  end
  resources :relationships,   only: [:create, :destroy]
  resources :favorites,       only: [:create, :destroy]
  resources :notifications,   only: [:index]
end

app/models/notification.rb
class Notification < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  belongs_to :post, optional: true
  belongs_to :comment, optional: true

  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @notifications = current_user.passive_notifications.page(params[:page]).per(20)
    @notifications.where(checked: false).each do |notification|
      notification.update_attributes(checked: true)
    end
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def unchecked_notifications
    @notifications = current_user.passive_notifications.where(checked: false)
  end
end

app/views/notifications/_notification.html.erb
<% visitor = notification.visitor %>
<% visited = notification.visited %>
<div class="col-md-6.mx-auto">
  <div class= "form-inline">
    <span>
      <strong>
      <%= image_tag visitor.avatar.url%>
      <%= link_to visitor.username,user_path(visitor) %>さんが
        <% case notification.action when "favorite" %>
          <%= link_to  "あなたの投稿", notification.post %>
          をお気に入りしました
        <% when "comment" %>
          <% if notification.post.user_id == visited.id  %>
            <%= link_to "あなたの投稿", notification.post %>
          <% else %>
            <%= image_tag notification.post.user.avatar.url, class: "icon_mini"%>
            <%= link_to "#{notification.post.username}さんの投稿",post_path(notification.post) %>
          <% end %>
          にコメントしました
            :  <%= Comment.find_by(id: notification.comment_id)&.text %>
        <% end %>
      </strong>
    </span>
  </div>
  <div class="small.text-muted.text-right">
    <%= time_ago_in_words(notification.created_at) %> ago
  </div>
</div>

app/views/notifications/index.html.erb
<%= provide(:title,"通知一覧") %>
<% @notifications = @notifications.where.not(visitor_id: current_user.id) %>
<h1>あなたへの通知</h1>
<ul>
  <%= render @notifications %>
  <%= paginate @notifications %>
</ul>