config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get '/riyo_kiyaku', to: 'static_pages#riyo_kiyaku'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: "users/registrations",
    sessions: "users/sessions",
    passwords: "users/passwords"
  }
  devise_scope :user do
    get    'users/signup', to: 'devise/registrations#new',    as: :new_user
    post   'users/signup', to: 'devise/registrations#create', as: :user_signup
    get    'users/login',  to: 'devise/sessions#new',         as: :new_user_login
    post   'users/login',  to: 'devise/sessions#create',      as: :user_login
    delete 'users/logout', to: 'devise/sessions#destroy',     as: :user_logout
  end

  resources :users,           only: [:index, :show] do
    member do
      get :edit_password
      patch :update_password
      get :following
      get :followers
      get :favorites
    end
  end

  resources :posts,           only: [:show, :new, :create, :destroy] do
    resources :comments,        only: [:create]
  end
  resources :relationships,   only: [:create, :destroy]
  resources :favorites,       only: [:create, :destroy]
  resources :notifications,   only: [:index]
end

app/views/layouts/_after_login_header.html.erb
<li class="search-nav">
    <%= form_tag(root_path, method: :get) do %>
      <div class="input-group">
        <%= search_field_tag "q", params[:q], class: "form-control", placeholder: "キーワード検索" %>
        <span class="input-group-btn">
          <%= submit_tag "検索", class: "btn btn-default" %>
        </span>
      </div>
    <% end %>
  <li><%= link_to notifications_path do %>
    <% if unchecked_notifications.any? %>
      <span class="fa-stack">
        <i class="fa fa-bell fa-stack-2x"></i>
        <i class="fa fa-circle fa-stack-1x"></i>
      </span>
    <% else %>
      <i class="fa fa-bell"></i>
    <% end %>
  <% end %>
  </li>
  <li><%= link_to favorites_user_path(current_user) do %>
    <i class="fa fa-heart"></i><% end %></li>
  <li><%= link_to  current_user do %>
    <i class="fa fa-user"></i><% end %></li>
  <li><%= link_to "ログアウト", user_logout_path, method: :delete %></li>
</li>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="footer_post">
    <% if user_signed_in? %>
      <%= link_to  new_post_path do %>
        <i class="fa fa-upload">投稿する</i>
      <% end %>
    <% end %>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Insta Clone", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Top", root_path %></li>
        <% if user_signed_in? %>
          <%= render  "layouts/after_login_header" %>
        <% else %>
          <li><%= link_to "ログイン", new_user_login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper">
      <%= render 'layouts/header' %>
      <div class="container">
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
        <%= yield %>
      </div>
      <%= render 'layouts/footer' %>
      
    </div>
  </body>
</html>